import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { Geist, Geist_Mono } from "next/font/google";
import { Button, HStack, AbsoluteCenter, Box } from "@chakra-ui/react";
import { LuHeart } from "react-icons/lu";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <Box position="relative" h="500px" bg="bg.muted" borderRadius="md">
            <AbsoluteCenter>Hello World!</AbsoluteCenter>
          </Box>
        </Provider>
      </body>
    </html>
  );
}
